service: serverless-flask-container

provider:
  name: aws
  region: us-west-2
  ecr:
    images:
      cloud-project-2:
        path: ./

functions:
  app:
    image:
      name: cloud-project-2
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
