service: cloud-project2

provider:
  name: aws
  region: us-west-2
  ecr:
    images:
      cloud-project2:
        path: ./

functions:
  app:
    image:
      name: cloud-project2
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
